#!/usr/bin/env python
"""Generate RULES.md from the rule registry.

Run `python scripts/gen_rules_doc.py` (or `uv run python scripts/gen_rules_doc.py`)
after adding/changing a rule. CI fails if the committed RULES.md is out of date.
"""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "src"))

from vgi_lint_check.findings import Category  # noqa: E402
from vgi_lint_check.rules.registry import all_rule_classes  # noqa: E402

CATEGORY_TITLES = {
    Category.CATALOG: "Catalog (VGI0xx)",
    Category.DISCOVERABILITY: "Discoverability (VGI12x)",
    Category.CONTENT: "Content — Markdown & links (VGI17x)",
    Category.DESCRIPTION: "Descriptions (VGI1xx)",
    Category.COLUMNS: "Columns (VGI2xx)",
    Category.FUNCTIONS: "Functions & macros (VGI3xx)",
    Category.TAGS: "Tags (VGI4xx)",
    Category.EXAMPLES: "Example queries (VGI5xx)",
    Category.SETTINGS: "Settings (VGI6xx)",
    Category.PRAGMAS: "Pragmas (VGI7xx)",
    Category.CONSTRAINTS: "Constraints (VGI8xx)",
    Category.STRUCTURE: "Structure & size limits (VGI11x/13x)",
    Category.ATTACH_OPTIONS: "Attach options (VGI10xx)",
    Category.EXECUTION: "Execution (VGI9xx)",
}

HEADER = """# vgi-lint rule reference

<!-- Generated by scripts/gen_rules_doc.py — do not edit by hand. -->

Every finding has a stable code (`VGIxxx`), a default severity, and a free-form
fix hint. Rules are configurable: enable/disable by code or category, override
severity, and ignore per object — see the [README](README.md#configuration).

Run `vgi-lint rules` to list these from your installed version, or
`vgi-lint explain VGI112` for one rule.

**Default severity** is what a rule emits unless overridden. `off` means the rule
is **opt-in** (enable it via `--severity CODE=warning` or config). Rules marked
**requires `--execute`** run example queries against the live worker and are
skipped unless `--execute` is passed.

"""


def _flags(cls) -> str:
    bits = []
    if cls.requires_connection:
        bits.append("requires `--execute`")
    if cls.default_severity.label == "off":
        bits.append("opt-in")
    return ", ".join(bits)


def render() -> str:
    by_cat: dict[Category, list] = {}
    for cls in all_rule_classes():
        by_cat.setdefault(cls.category, []).append(cls)

    out = [HEADER]
    total = 0
    for cat, title in CATEGORY_TITLES.items():
        rules = sorted(by_cat.get(cat, []), key=lambda c: c.code)
        if not rules:
            continue
        out.append(f"## {title}\n")
        out.append("| Code | Default | Rule | What it checks | Notes |")
        out.append("| --- | --- | --- | --- | --- |")
        for cls in rules:
            total += 1
            out.append(
                f"| `{cls.code}` | {cls.default_severity.label} | {cls.name} | "
                f"{cls.summary} | {_flags(cls)} |"
            )
        out.append("")
    out.append(f"_{total} rules._\n")
    return "\n".join(out)


def main() -> int:
    target = ROOT / "RULES.md"
    content = render()
    if "--check" in sys.argv:
        current = target.read_text() if target.exists() else ""
        if current != content:
            print("RULES.md is out of date; run: python scripts/gen_rules_doc.py")
            return 1
        print("RULES.md is up to date.")
        return 0
    target.write_text(content)
    print(f"wrote {target.relative_to(ROOT)} ({content.count(chr(10))} lines)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
